# Generated by Django 2.2.6 on 2020-12-09 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_teacher', models.CharField(default='', max_length=255)),
                ('s_teacher_country', django_countries.fields.CountryField(max_length=2)),
                ('s_photo', models.ImageField(default='', upload_to='sharing/')),
                ('s_appreciation', models.CharField(default='', max_length=160)),
                ('s_date', models.DateField()),
                ('s_location', models.CharField(max_length=30)),
                ('s_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['s_date'],
            },
        ),
    ]
