# Generated by Django 2.2.6 on 2020-12-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='s_video_dance',
            field=models.FileField(default='', upload_to='dance/'),
        ),
        migrations.AddField(
            model_name='sharing',
            name='s_video_talk',
            field=models.FileField(default='', upload_to='talk/'),
        ),
    ]
