# Generated by Django 2.2.6 on 2021-01-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_auto_20210115_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='c_shareid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_sharing', to='sharing.Sharing'),
        ),
        migrations.AlterField(
            model_name='likestosharing',
            name='l_shareid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sharing', to='sharing.Sharing'),
        ),
    ]
