# Generated by Django 2.2.6 on 2020-12-09 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing', '0002_auto_20201209_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='voters_like',
            field=models.ManyToManyField(related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
