# Generated by Django 2.2.6 on 2020-12-09 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_sharing_voters_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='s_teacher_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='s_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
