# Generated by Django 2.2.6 on 2020-12-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='s_date',
            field=models.DateField(auto_now=True),
        ),
    ]
