# Generated by Django 2.2.6 on 2020-09-17 09:08

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import portfolio.urls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default='', upload_to='uploads/')),
                ('text', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('style', models.CharField(default='', max_length=15)),
                ('artist_image', models.FileField(default='', upload_to=portfolio.urls.Portfolio.scramble_uploaded_filename)),
                ('bio', models.CharField(default='', max_length=100)),
                ('introduction', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('bi_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio.Portfolio')),
                ('bi_content', portfolio.urls.NonStrippingTextField()),
                ('bi_photo1', models.ImageField(default='', upload_to='biography/')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=50)),
                ('w_dancestyle', models.CharField(choices=[('', ''), ('HipHop', 'HipHop'), ('HipHop Freestyle', 'HipHop Freestyle'), ('Breaking', 'Breaking'), ('House', 'House'), ('Locking', 'Locking'), ('Popping', 'Popping'), ('Waacking', 'Waacking'), ('Krump', 'Krump'), ('Vouge', 'Vouge'), ('Litefeet', 'Litefeet'), ('Tutting', 'Tutting'), ('Flexing', 'Flexing'), ('Footwork', 'Footwork'), ('Handstyle', 'Handstyle'), ('Waving', 'Waving'), ('Animation', 'Animation'), ('Urban', 'Urban'), ('Choreography', 'Choreography'), ('Freestyle', 'Freestyle'), ('Afro', 'Afro'), ('Jazz', 'Jazz'), ('Salsa', 'Salsa'), ('Contemporary', 'Contemporary'), ('Experimental', 'Experimental')], default='', max_length=50)),
                ('w_content', models.CharField(max_length=50)),
                ('w_country', django_countries.fields.CountryField(max_length=2)),
                ('w_location', models.CharField(max_length=20)),
                ('w_date', models.DateTimeField()),
                ('w_photo', models.ImageField(default='', upload_to=portfolio.urls.Workshop.scramble_uploaded_filename)),
                ('w_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='portfolio.Portfolio')),
            ],
            options={
                'ordering': ['-w_date'],
            },
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_title', models.CharField(max_length=100)),
                ('t_content', models.CharField(max_length=50000)),
                ('t_photo', models.ImageField(default='', upload_to=portfolio.urls.Thought.scramble_uploaded_filename)),
                ('t_date', models.DateField()),
                ('t_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought', to='portfolio.Portfolio')),
            ],
            options={
                'ordering': ['-t_date'],
            },
        ),
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_photo', models.ImageField(default='', upload_to='sharing/')),
                ('s_appreciation', models.CharField(default='', max_length=160)),
                ('s_where_u_met', models.CharField(default='', max_length=100)),
                ('s_date', models.DateField()),
                ('s_country', django_countries.fields.CountryField(max_length=2)),
                ('s_location', models.CharField(max_length=30)),
                ('s_photo_comment', models.ImageField(default='', upload_to='sharing/')),
                ('s_student', models.ManyToManyField(related_name='mystudent', to='portfolio.Portfolio')),
                ('s_teacher', models.ManyToManyField(related_name='myteacher', to='portfolio.Portfolio')),
            ],
            options={
                'ordering': ['s_date'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_what_happend', models.CharField(max_length=100)),
                ('m_context', models.CharField(default='', max_length=255)),
                ('m_date', models.DateField(default='')),
                ('m_photo', models.ImageField(default='', upload_to=portfolio.urls.Milestone.scramble_uploaded_filename)),
                ('m_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='portfolio.Portfolio')),
            ],
            options={
                'ordering': ['-m_date'],
            },
        ),
        migrations.CreateModel(
            name='Judging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_event_name', models.CharField(max_length=50)),
                ('j_dancestyle', models.CharField(choices=[('', ''), ('HipHop', 'HipHop'), ('HipHop Freestyle', 'HipHop Freestyle'), ('Breaking', 'Breaking'), ('House', 'House'), ('Locking', 'Locking'), ('Popping', 'Popping'), ('Waacking', 'Waacking'), ('Krump', 'Krump'), ('Vouge', 'Vouge'), ('Litefeet', 'Litefeet'), ('Tutting', 'Tutting'), ('Flexing', 'Flexing'), ('Footwork', 'Footwork'), ('Handstyle', 'Handstyle'), ('Waving', 'Waving'), ('Animation', 'Animation'), ('Urban', 'Urban'), ('Choreography', 'Choreography'), ('Freestyle', 'Freestyle'), ('Afro', 'Afro'), ('Jazz', 'Jazz'), ('Salsa', 'Salsa'), ('Contemporary', 'Contemporary'), ('Experimental', 'Experimental')], default='', max_length=50)),
                ('j_country', django_countries.fields.CountryField(max_length=2)),
                ('j_location', models.CharField(max_length=20)),
                ('j_date', models.DateField()),
                ('j_event_photo', models.ImageField(default='', upload_to=portfolio.urls.Judging.scramble_uploaded_filename)),
                ('j_judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='portfolio.Portfolio')),
            ],
            options={
                'ordering': ['-j_date'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_upload_photo', models.ImageField(default='', upload_to=portfolio.urls.Gallery.scramble_uploaded_filename)),
                ('g_datetime', models.DateTimeField(auto_now=True)),
                ('g_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.Portfolio')),
            ],
            options={
                'ordering': ['-g_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(default='', max_length=255)),
                ('b_date', models.DateField()),
                ('b_content', models.TextField(default='')),
                ('b_photo', models.ImageField(default='', upload_to='blog/')),
                ('b_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='portfolio.Portfolio')),
            ],
            options={
                'ordering': ['b_date'],
            },
        ),
    ]
