# Generated by Django 2.2.6 on 2020-07-13 01:34

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=50)),
                ('w_dancestyle', models.CharField(choices=[('', ''), ('HipHop', 'HipHop'), ('HipHop Freestyle', 'HipHop Freestyle'), ('Breaking', 'Breaking'), ('House', 'House'), ('Locking', 'Locking'), ('Popping', 'Popping'), ('Waacking', 'Waacking'), ('Krump', 'Krump'), ('Vouge', 'Vouge'), ('Litefeet', 'Litefeet'), ('Tutting', 'Tutting'), ('Flexing', 'Flexing'), ('Footwork', 'Footwork'), ('Handstyle', 'Handstyle'), ('Waving', 'Waving'), ('Animation', 'Animation'), ('Urban', 'Urban'), ('Choreography', 'Choreography'), ('Freestyle', 'Freestyle'), ('Afro', 'Afro'), ('Jazz', 'Jazz'), ('Salsa', 'Salsa'), ('Contemporary', 'Contemporary'), ('Experimental', 'Experimental')], default='', max_length=50)),
                ('w_content', models.CharField(max_length=50)),
                ('w_country', django_countries.fields.CountryField(max_length=2)),
                ('w_location', models.CharField(max_length=20)),
                ('w_date', models.DateTimeField()),
                ('w_photo', models.ImageField(default='', height_field=50, upload_to='workshop/images', width_field=50)),
                ('w_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='portfolio.Portfolio')),
            ],
        ),
    ]
