# Generated by Django 2.2.6 on 2020-07-13 01:49

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_workshop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='artist',
            new_name='artist_name',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='artist_image',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='bio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='style',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.CreateModel(
            name='Judging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_event_name', models.CharField(max_length=50)),
                ('j_dancestyle', models.CharField(choices=[('', ''), ('HipHop', 'HipHop'), ('HipHop Freestyle', 'HipHop Freestyle'), ('Breaking', 'Breaking'), ('House', 'House'), ('Locking', 'Locking'), ('Popping', 'Popping'), ('Waacking', 'Waacking'), ('Krump', 'Krump'), ('Vouge', 'Vouge'), ('Litefeet', 'Litefeet'), ('Tutting', 'Tutting'), ('Flexing', 'Flexing'), ('Footwork', 'Footwork'), ('Handstyle', 'Handstyle'), ('Waving', 'Waving'), ('Animation', 'Animation'), ('Urban', 'Urban'), ('Choreography', 'Choreography'), ('Freestyle', 'Freestyle'), ('Afro', 'Afro'), ('Jazz', 'Jazz'), ('Salsa', 'Salsa'), ('Contemporary', 'Contemporary'), ('Experimental', 'Experimental')], default='', max_length=50)),
                ('j_country', django_countries.fields.CountryField(max_length=2)),
                ('j_location', models.CharField(max_length=20)),
                ('j_date', models.DateField()),
                ('j_event_photo', models.ImageField(default='', height_field=50, upload_to='judging/images', width_field=50)),
                ('j_judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='portfolio.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_upload_photo', models.ImageField(default='', height_field=50, upload_to='gallery/images', width_field=50)),
                ('g_datetime', models.DateTimeField(auto_now=True)),
                ('g_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.Portfolio')),
            ],
        ),
    ]
