# Generated by Django 2.2.6 on 2020-07-13 02:11

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200713_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
