# Generated by Django 2.2.6 on 2020-07-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200713_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='g_upload_photo',
            field=models.ImageField(default='', upload_to='gallery/images'),
        ),
        migrations.AlterField(
            model_name='judging',
            name='j_event_photo',
            field=models.ImageField(default='', upload_to='judging/images'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='artist_image',
            field=models.FileField(default='', upload_to='portfolio/images'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='w_photo',
            field=models.ImageField(default='', upload_to='workshop/images/scramble_uploaded_filename'),
        ),
    ]
