# Generated by Django 2.2.6 on 2020-07-15 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200713_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_title', models.CharField(max_length=100)),
                ('t_content', models.CharField(max_length=50000)),
                ('t_photo', models.ImageField(default='', upload_to='thoughtsnippet/scramble_uploaded_filename')),
                ('t_date', models.DateField()),
                ('t_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughtsnippets', to='portfolio.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_what_happend', models.CharField(max_length=100)),
                ('m_context', models.CharField(default='', max_length=500)),
                ('m_date', models.DateField(default='')),
                ('m_photo', models.ImageField(default='', upload_to='milestone/scramble_uploaded_filename')),
                ('m_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='portfolio.Portfolio')),
            ],
        ),
    ]
