# Generated by Django 2.2.6 on 2020-07-18 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_milestone_thought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='t_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought', to='portfolio.Portfolio'),
        ),
    ]
