# Generated by Django 2.2.6 on 2020-07-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200718_0616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-g_datetime']},
        ),
        migrations.AddField(
            model_name='gallery',
            name='g_resized_photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
