# Generated by Django 2.2.6 on 2020-07-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200720_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='g_resized_photo',
            new_name='g_resized_photo_path',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='g_upload_photo',
            field=models.ImageField(default='', upload_to='gallery/1595236751/'),
        ),
    ]
