# Generated by Django 2.2.6 on 2020-07-31 09:05

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200722_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='g_resized_photo_path',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='g_resizedpath',
        ),
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_photo', models.ImageField(default='', upload_to='sharing/')),
                ('s_appreciation', models.CharField(default='', max_length=160)),
                ('s_where_u_met', models.CharField(default='', max_length=100)),
                ('s_date', models.DateField()),
                ('s_country', django_countries.fields.CountryField(max_length=2)),
                ('s_location', models.CharField(max_length=30)),
                ('s_student', models.ManyToManyField(related_name='student', to='portfolio.Portfolio')),
                ('s_teacher', models.ManyToManyField(related_name='teacher', to='portfolio.Portfolio')),
            ],
            options={
                'ordering': ['s_date'],
            },
        ),
    ]
