# Generated by Django 2.2.6 on 2020-08-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20200806_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='biography',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Biography',
        ),
    ]
