# Generated by Django 2.2.6 on 2020-08-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20200806_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_photo', models.ImageField(default='', upload_to='uploads/')),
            ],
        ),
    ]
