# Generated by Django 2.2.6 on 2020-08-23 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_fileupload_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(default='', max_length=255)),
                ('b_date', models.DateField()),
                ('b_content', models.TextField(default='')),
                ('b_photo', models.ImageField(default='', upload_to='blog/')),
                ('b_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='portfolio.Portfolio')),
            ],
            options={
                'ordering': ['b_date'],
            },
        ),
    ]
