# Generated by Django 2.2.6 on 2021-02-22 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joevent', models.CharField(default='', max_length=255)),
                ('jophoto', models.ImageField(default='', upload_to='events_attended/')),
                ('jodate', models.DateField(blank=True, null=True)),
                ('jocontent', models.TextField(blank=True, default='')),
                ('jolink', models.URLField(blank=True, default='', max_length=255)),
                ('joartist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_context', models.CharField(default='', max_length=255)),
                ('h_photo', models.ImageField(default='', upload_to='work/')),
                ('h_date', models.DateField(blank=True, null=True)),
                ('h_content', models.TextField(blank=True, default='')),
                ('h_link', models.URLField(blank=True, default='')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, default='', max_length=15)),
                ('quote', models.CharField(blank=True, default='', max_length=255)),
                ('introduction', models.TextField(blank=True, default='')),
                ('crew', models.CharField(blank=True, default='', max_length=255)),
                ('ig', models.URLField(blank=True, default='')),
                ('fb', models.URLField(blank=True, default='')),
                ('site', models.URLField(blank=True, default='')),
                ('gallery1', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('gallery2', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('gallery3', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('gallery4', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artistdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, default='', upload_to='covers/')),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to='thumbnails/')),
                ('country', django_countries.fields.CountryField(blank=True, default='', max_length=2)),
                ('artist_name', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
