# Generated by Django 2.2.6 on 2021-02-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistdata',
            old_name='ownerdata',
            new_name='owner',
        ),
    ]
