# Generated by Django 2.2.6 on 2021-01-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='ev_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='h_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='judgingworkshop',
            name='jw_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
