# Generated by Django 2.2.6 on 2020-12-05 16:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='introduction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='quote',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='style',
            field=models.CharField(default='', max_length=15),
        ),
    ]
