# Generated by Django 2.2.6 on 2020-12-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20201205_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='wuser',
            new_name='w_artist',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='wcontext',
            new_name='w_context',
        ),
        migrations.AddField(
            model_name='work',
            name='w_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='w_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='work',
            name='w_photo',
            field=models.ImageField(default='', upload_to='work/'),
        ),
    ]
