# Generated by Django 2.2.6 on 2020-10-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20201019_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='username',
        ),
    ]
