# Generated by Django 2.2.6 on 2021-01-13 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20210105_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='b_artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
