# Generated by Django 2.2.6 on 2020-10-20 07:47

import artist.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0003_auto_20201019_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_upload_photo', models.ImageField(default='', upload_to=artist.models.Gallery.scramble_uploaded_filename)),
                ('g_datetime', models.DateTimeField(auto_now=True)),
                ('g_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-g_datetime'],
            },
        ),
    ]
