# Generated by Django 2.2.6 on 2021-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20210218_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistdata',
            name='gallery1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='artistdata',
            name='gallery2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='artistdata',
            name='gallery3',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='artistdata',
            name='gallery4',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
