# Generated by Django 2.2.6 on 2020-12-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20201207_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='username',
            new_name='name',
        ),
    ]
