# Generated by Django 2.2.6 on 2020-12-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20201208_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='username',
        ),
    ]
