# Generated by Django 2.2.6 on 2020-10-26 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_auto_20201026_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL),
        ),
    ]
