# Generated by Django 2.2.6 on 2020-12-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_auto_20201208_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='fb',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='ig',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='personal',
            field=models.CharField(default='', max_length=255),
        ),
    ]
