# Generated by Django 2.2.6 on 2020-12-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_auto_20201220_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='crew',
            field=models.CharField(default='', max_length=255),
        ),
    ]
