# Generated by Django 2.2.6 on 2020-12-28 02:10

import artist.models
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0009_auto_20201228_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='crew',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='fb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='ig',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='personal',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='quote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='style',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='ev_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='ev_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='ev_event',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='ev_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='ev_photo',
            field=models.ImageField(null=True, upload_to='events_attended/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='g_upload_photo',
            field=models.ImageField(null=True, upload_to=artist.models.Gallery.scramble_uploaded_filename),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='w_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='w_context',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='w_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='w_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='w_photo',
            field=models.ImageField(null=True, upload_to='work/'),
        ),
        migrations.AlterField(
            model_name='judgingworkshop',
            name='jw_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='judgingworkshop',
            name='jw_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='judgingworkshop',
            name='jw_event',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='judgingworkshop',
            name='jw_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='judgingworkshop',
            name='jw_photo',
            field=models.ImageField(null=True, upload_to='judgingworkshop/'),
        ),
    ]
