# Generated by Django 2.2.6 on 2020-07-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200713_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='g_upload_photo',
            field=models.ImageField(default='', upload_to='gallery/images/scramble_uploaded_filename'),
        ),
        migrations.AlterField(
            model_name='judging',
            name='j_event_photo',
            field=models.ImageField(default='', upload_to='judging/images/scramble_uploaded_filename'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='artist_image',
            field=models.FileField(default='', upload_to='portfolio/images/scramble_uploaded_filename'),
        ),
    ]
